package Mailfull::Setup::Dovecot;

use strict;
use warnings;
use diagnostics;


##############################
# dovecot config
##############################
sub setup {
    my $self = shift;

    print "generate dovecot configuration, save into $Mailfull::Core::Cfg->{dir_etc}\n";

    my $uid = getpwnam $Mailfull::Core::Cfg->{username};
    my $gid = getgrnam $Mailfull::Core::Cfg->{groupname};

    if ( ! defined($uid) || ! defined($gid) ) {
        return;
    }

    my $time = localtime(time);

    my $conf_1 = << "___EOL___";
# Generated by mailfull on $time

protocols = imap imaps pop3 pop3s
mail_location = maildir:~/Maildir

ssl_disable = no
ssl_cert_file = /etc/pki/dovecot/certs/dovecot.pem
ssl_key_file = /etc/pki/dovecot/private/dovecot.pem
#ssl_ca_file = 

#disable_plaintext_auth = no

auth default {
  mechanisms = plain login

  passdb passwd-file {
    args = $Mailfull::Core::Cfg->{path_passwds}
  }
  passdb pam {
  }
  userdb passwd {
  }
  userdb static {
    args = uid=$uid gid=$gid home=$Mailfull::Core::Cfg->{dir_data}/\%d/\%n
  }

  socket listen {
    client {
      path = /var/spool/postfix/private/auth
      mode = 0660
      user = postfix
      group = postfix
    }
  }
}

___EOL___

    my $conf_2 = << "___EOL___";
# Generated by mailfull on $time

protocols = imap pop3
auth_mechanisms = plain login
mail_location = maildir:~/Maildir

ssl = yes
ssl_cert = </etc/pki/dovecot/certs/dovecot.pem
ssl_key = </etc/pki/dovecot/private/dovecot.pem
#ssl_ca = 

#disable_plaintext_auth = no

passdb {
  driver = passwd-file
  args = $Mailfull::Core::Cfg->{path_passwds}
}
passdb {
  driver = pam
}
userdb {
  driver = passwd
}
userdb {
  driver = static
  args = uid=$Mailfull::Core::Cfg->{username} gid=$Mailfull::Core::Cfg->{groupname} home=$Mailfull::Core::Cfg->{dir_data}/\%d/\%n
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0666
    user = postfix
    group = postfix
  }
}

___EOL___

    Mailfull::Utils::File->touch("$Mailfull::Core::Cfg->{dir_etc}/dovecot.conf.sample.1", $Mailfull::Core::Cfg->{umask_etc});
    open(my $fh_out1, '>', "$Mailfull::Core::Cfg->{dir_etc}/dovecot.conf.sample.1") or die "$!";
    print $fh_out1 $conf_1;
    close($fh_out1) or die "$!";

    Mailfull::Utils::File->touch("$Mailfull::Core::Cfg->{dir_etc}/dovecot.conf.sample.2", $Mailfull::Core::Cfg->{umask_etc});
    open(my $fh_out2, '>', "$Mailfull::Core::Cfg->{dir_etc}/dovecot.conf.sample.2") or die "$!";
    print $fh_out2 $conf_2;
    close($fh_out2) or die "$!";
}


1;

