package Mailfull::Setup::Postfix;

use strict;
use warnings;
use diagnostics;


##############################
# generate main.cf
##############################
sub setup {
    my $self = shift;

    print "generate postfix configuration, save into $Mailfull::Core::Cfg->{dir_etc}\n";

    my $uid = getpwnam $Mailfull::Core::Cfg->{username};
    my $gid = getgrnam $Mailfull::Core::Cfg->{groupname};

    if ( ! defined($uid) || ! defined($gid) ) {
        return;
    }

    my $time = localtime(time);

    my $conf = << "___EOL___";
# Generated by mailfull on $time

#myhostname = host.example.com
mydomain = \$myhostname
myorigin = \$mydomain

inet_interfaces = all
mydestination = \$myhostname, localhost.\$mydomain, localhost, \$mydomain
mynetworks_style = host
recipient_delimiter = -
message_size_limit = 10240000
mailbox_size_limit = 51200000
virtual_mailbox_limit = 51200000

virtual_mailbox_domains = hash:$Mailfull::Core::Cfg->{path_domains}
virtual_mailbox_base = $Mailfull::Core::Cfg->{dir_data}
virtual_mailbox_maps = hash:$Mailfull::Core::Cfg->{path_maildirs}
virtual_uid_maps = static:$uid
virtual_gid_maps = static:$gid
virtual_alias_maps = hash:$Mailfull::Core::Cfg->{path_destinations}
transport_maps = regexp:$Mailfull::Core::Cfg->{path_localtable}
alias_maps = hash:/etc/aliases, hash:$Mailfull::Core::Cfg->{path_forwards}
alias_database = hash:/etc/aliases, hash:$Mailfull::Core::Cfg->{path_forwards}

smtpd_sasl_auth_enable = yes
smtpd_sasl_local_domain = \$myhostname
smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth

smtpd_tls_cert_file = /etc/pki/dovecot/certs/dovecot.pem
smtpd_tls_key_file = /etc/pki/dovecot/private/dovecot.pem
#smtpd_tls_CAfile = 
smtpd_tls_session_cache_database = btree:/etc/postfix/smtpd_scache

___EOL___

    Mailfull::Utils::File->touch("$Mailfull::Core::Cfg->{dir_etc}/main.cf.sample", $Mailfull::Core::Cfg->{umask_etc});
    open(my $fh_out, '>', "$Mailfull::Core::Cfg->{dir_etc}/main.cf.sample") or die "$!";
    print $fh_out $conf;
    close($fh_out) or die "$!";
}


1;

